ep3/ep3/urls.py
from django.contrib import admin
from django.urls import include,path

urlpatterns = [
    path('gerenciamentoPEA/', include('gerenciamentoPEA.urls')),
    path('admin/', admin.site.urls),
]

ep3/gerenciamentoPEA/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    
    path('pacientes/', views.pacientes, name='pacientes'),
    path('pacientes/add_paciente/', views.add_paciente, name='add_paciente'),
    path('pacientes/save_paciente/', views.save_paciente, name='save_paciente'),
    path('pacientes/<int:id_paciente>/change_paciente', views.change_paciente, name='change_paciente'),
    path('pacientes/<int:id_paciente>/delete_paciente', views.delete_paciente, name='delete_paciente'),
    path('pacientes/<int:id_paciente>/', views.paciente_detail, name='p_detalhes'),
    path('pacientes/<int:id_paciente>/exames/', views.exames_do_paciente, name='p_exames'),

    path('exames/', views.exames, name='exames'),
    path('exames/<int:id_exame>/', views.exame_detail, name='e_detalhes'),
    path('exames/adiciona_exame/', views.add_exame, name='add_exame'),
    path('exames/save_exame/', views.save_exame, name='save_exame'),
    path('exames/<int:id_exame>/change_exame', views.change_exame, name='change_exame'),
    path('exames/<int:id_exame>/delete_exame', views.delete_exame, name='delete_exame'),

    path('amostras/', views.amostras, name='amostras'),
    path('amostras/add_amostra/', views.add_amostra, name='add_amostra'),
    path('amostras/save_amostra/', views.save_amostra, name='save_amostra'),
    path('amostras/<int:id_amostra>/change_amostra', views.change_amostra, name='change_amostra'),
    path('amostras/<int:id_amostra>/delete_amostra', views.delete_amostra, name='delete_amostra'),
    path('amostras/<int:id_amostra>/', views.amostra_detail, name='a_detalhes'),

    path('agregadoPEAs/', views.agregadoPEAs, name='agregadoPEAs'),
    path('agregadoPEAs/<int:id_agregadoPEA>/', views.agregadoPEA_detail, name='ag_detalhes'),
    path('agregadoPEAs/adiciona_agregadoPEA/', views.add_agregadoPEA, name='add_agregadoPEA'),
    path('agregadoPEAs/save_agregadoPEA/', views.save_agregadoPEA, name='save_agregadoPEA'),
    path('agregadoPEAs/<int:id_agregadoPEA>/change_agregadoPEA', views.change_agregadoPEA, name='change_agregadoPEA'),
    path('agregadoPEAs/<int:id_agregadoPEA>/delete_agregadoPEA', views.delete_agregadoPEA, name='delete_agregadoPEA'),
]

ep3/gerenciamentoPEA/models.py
from django.db import models
from django.db.models.fields import DateField

# Create your models here.

class Paciente(models.Model):
    id_paciente = models.IntegerField(primary_key=True)
    cpf = models.CharField(max_length=11, unique=True)
    nome = models.CharField(max_length=255)
    endereco = models.CharField(max_length=255)
    nascimento = models.DateField()

class Exame(models.Model):
    id_exame = models.IntegerField(primary_key=True)
    tipo = models.CharField(max_length=255)
    virus = models.CharField(max_length=255)
    id_paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    class Meta:
        unique_together = ('tipo', 'virus',)

class Amostra(models.Model):
    id_amostra = models.IntegerField(primary_key=True)
    codigo_amostra = models.CharField(max_length=255, unique=True)
    metodo_de_coleta = models.CharField(max_length=255)
    material = models.CharField(max_length=255)

class Paciente_exame_amostra(models.Model):
    id_paciente = models.ForeignKey(Paciente, on_delete=models.CASCADE)
    id_exame = models.ForeignKey(Exame, on_delete=models.CASCADE)
    id_amostra = models.ForeignKey(Amostra, on_delete=models.CASCADE)
    data_de_realizacao = models.DateTimeField()
    data_de_solicitacao = models.DateTimeField()
    class Meta:
        unique_together = ('id_paciente', 'id_exame', 'id_amostra', 'data_de_realizacao')

ep3/gerenciamentoPEA/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, Http404, HttpResponseRedirect
from .models import Paciente, Paciente_exame_amostra, Exame, Amostra
from django.template import loader
from django.urls import reverse
from datetime import datetime
# Create your views here.

def index(request):
    template = loader.get_template('gerenciamentoPEA/index.html')
    return render(request, 'gerenciamentoPEA/index.html', {})

# Paciente

def pacientes(request):
    paciente_list = Paciente.objects.order_by('cpf')
    return render(request, 'gerenciamentoPEA/pacientes.html', {'paciente_list': paciente_list})

def paciente_detail(request, id_paciente):
    paciente = get_object_or_404(Paciente, pk=id_paciente)
    return render(request, 'gerenciamentoPEA/paciente_detalhes.html', {'paciente': paciente})

def add_paciente(request):
    return render(request, 'gerenciamentoPEA/add_paciente.html', {})

def save_paciente(request):
    try:
        p = Paciente(id_paciente=request.POST['id_paciente'], cpf=request.POST['cpf'], nome=request.POST['nome'], endereco=request.POST['endereco'], nascimento=request.POST['nascimento'])
    except (KeyError):
        # Redisplay the question voting form.
        return render(request, 'gerenciamentoPEA/add_paciente.html', {
            'error_message': "Deu erro para cadastrar o paciente",
        })
    else:
        p.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'gerenciamentoPEA/save_paciente.html', {'paciente': p})

def change_paciente(request, id_paciente):
    paciente = get_object_or_404(Paciente, pk=id_paciente)
    return render(request, 'gerenciamentoPEA/change_paciente.html', {'paciente': paciente})

def delete_paciente(request, id_paciente):
    Paciente.objects.filter(id_paciente=id_paciente).delete()
    return render(request, 'gerenciamentoPEA/delete_paciente.html', {})

# Exames

def exames(request):
    exame_list = Exame.objects.order_by('id_exame')
    return render(request, 'gerenciamentoPEA/exames.html', {'exame_list': exame_list})

def add_exame(request):
    paciente_list = Paciente.objects.order_by('id_paciente')
    return render(request, 'gerenciamentoPEA/add_exame.html', {'paciente_list': paciente_list})

def exame_detail(request, id_exame):
    exame = get_object_or_404(Exame, pk=id_exame)
    return render(request, 'gerenciamentoPEA/exame_detalhes.html', {'exame': exame})

def exames_do_paciente(request, id_paciente):
    response = "Você está olhando para os exames do paciente %s."
    return HttpResponse(response % id_paciente)

def save_exame(request):
    try:
        p = get_object_or_404(Paciente, pk=request.POST['id_paciente'])
        try:
            Exame.objects.filter(id_exame=request.POST['id_exame']).delete()
        except:
            pass
        p.exame_set.create(id_exame=request.POST['id_exame'], tipo=request.POST['tipo'], virus=request.POST['virus'])
    except (KeyError):
        # Redisplay the question voting form.
        return render(request, 'gerenciamentoPEA/add_exame.html', {
            'error_message': "Deu erro para cadastrar o exame",
        })
    else:
        p.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'gerenciamentoPEA/save_exame.html', {'paciente': p})
    
def change_exame(request, id_exame):
    exame = get_object_or_404(Exame, pk=id_exame)
    paciente_list = Paciente.objects.order_by('id_paciente')
    return render(request, 'gerenciamentoPEA/change_exame.html', {'exame': exame, 'paciente_list':paciente_list})

def delete_exame(request, id_exame):
    Exame.objects.filter(id_exame=id_exame).delete()
    return render(request, 'gerenciamentoPEA/delete_exame.html', {})

# Amostra

def amostras(request):
    amostra_list = Amostra.objects.order_by('id_amostra')
    return render(request, 'gerenciamentoPEA/amostras.html', {'amostra_list': amostra_list})

def amostra_detail(request, id_amostra):
    amostra = get_object_or_404(Amostra, pk=id_amostra)
    return render(request, 'gerenciamentoPEA/amostra_detalhes.html', {'amostra': amostra})

def add_amostra(request):
    return render(request, 'gerenciamentoPEA/add_amostra.html', {})

def save_amostra(request):
    try:
        a = Amostra(id_amostra=request.POST['id_amostra'], codigo_amostra=request.POST['codigo_amostra'], metodo_de_coleta=request.POST['metodo_de_coleta'], material=request.POST['material'])
    except (KeyError):
        # Redisplay the question voting form.
        return render(request, 'gerenciamentoPEA/add_amostra.html', {
            'error_message': "Deu erro para cadastrar a amostra",
        })
    else:
        a.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'gerenciamentoPEA/save_amostra.html', {'amostra': a})

def change_amostra(request, id_amostra):
    amostra = get_object_or_404(Amostra, pk=id_amostra)
    return render(request, 'gerenciamentoPEA/change_amostra.html', {'amostra': amostra})

def delete_amostra(request, id_amostra):
    Amostra.objects.filter(id_amostra=id_amostra).delete()
    return render(request, 'gerenciamentoPEA/delete_amostra.html', {})

# Agregado Paciente_exame_amostra

def agregadoPEAs(request):
    agregadoPEA_list = Paciente_exame_amostra.objects.order_by('id')
    return render(request, 'gerenciamentoPEA/agregadoPEAs.html', {'agregadoPEA_list': agregadoPEA_list})

def add_agregadoPEA(request):
    paciente_list = Paciente.objects.order_by('id_paciente')
    exame_list = Exame.objects.order_by('id_exame')
    amostra_list = Amostra.objects.order_by('id_amostra')
    return render(request, 'gerenciamentoPEA/add_agregadoPEA.html', {'paciente_list': paciente_list,'amostra_list': amostra_list,'exame_list': exame_list})

def agregadoPEA_detail(request, id_agregadoPEA):
    agregadoPEA = get_object_or_404(Paciente_exame_amostra, pk=id_agregadoPEA)
    return render(request, 'gerenciamentoPEA/agregadoPEA_detalhes.html', {'agregadoPEA': agregadoPEA})

def save_agregadoPEA(request):
    paciente = get_object_or_404(Paciente, pk=request.POST['id_paciente'])
    exame = get_object_or_404(Exame, pk=request.POST['id_exame'])
    amostra = get_object_or_404(Amostra, pk=request.POST['id_amostra'])
    try:
        try:#se ja existir o agregado, deleta e atualiza as informações
            Paciente_exame_amostra.objects.filter(id_paciente=paciente, id_exame=exame, id_amostra=amostra).delete()
        except:
            pass
        ag = Paciente_exame_amostra(id_paciente=paciente, id_exame=exame, id_amostra=amostra, data_de_realizacao=(request.POST['data_de_realizacao_0'] + ' ' + request.POST['data_de_realizacao_1']), data_de_solicitacao=(request.POST['data_de_solicitacao_0']+' '+request.POST['data_de_solicitacao_1']))
    except (KeyError):
        return render(request, 'gerenciamentoPEA/add_agregadoPEA.html', {
            'error_message': "Deu erro para cadastrar o Paciente_exame_amostra",
        })
    else:
        ag.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return render(request, 'gerenciamentoPEA/save_agregadoPEA.html', {'paciente': ag})
    
def change_agregadoPEA(request, id_agregadoPEA):
    paciente_list = Paciente.objects.order_by('id_paciente')
    exame_list = Exame.objects.order_by('id_exame')
    amostra_list = Amostra.objects.order_by('id_amostra')
    agregadoPEA = get_object_or_404(Paciente_exame_amostra, pk=id_agregadoPEA)
    return render(request, 'gerenciamentoPEA/change_agregadoPEA.html', {'agregadoPEA':agregadoPEA, 'paciente_list': paciente_list,'amostra_list': amostra_list,'exame_list': exame_list})

def delete_agregadoPEA(request, id_agregadoPEA):
    Paciente_exame_amostra.objects.filter(id=id_agregadoPEA).delete()
    return render(request, 'gerenciamentoPEA/delete_agregadoPEA.html', {})

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/add_amostra.html
<h1>Cadastre Amostra</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'save_amostra'%}" method="post">
    {% csrf_token %}
    <div>
        <fieldset class="module aligned ">
                <div class="form-row field-id_amostra">
                        <div>
                                <label class="required" for="id_id_amostra">Id amostra:</label>
                                    <input type="number" name="id_amostra" class="vIntegerField" required="" id="id_id_amostra">
                        </div>
                </div>
                <div class="form-row field-codigo_amostra">
                        <div>
                                <label class="required" for="id_codigo_amostra">Codigo amostra:</label>
                                    <input type="text" name="codigo_amostra" class="vTextField" maxlength="255" required="" id="id_codigo_amostra">
                        </div>
                </div>
                <div class="form-row field-metodo_de_coleta">
                        <div>
                                <label class="required" for="id_metodo_de_coleta">Metodo de coleta:</label>
                                    <input type="text" name="metodo_de_coleta" class="vTextField" maxlength="255" required="" id="id_metodo_de_coleta">
                        </div>
                </div>
                <div class="form-row field-material">
                        <div>
                                <label class="required" for="id_material">Material:</label>
                                    <input type="text" name="material" class="vTextField" maxlength="255" required="" id="id_material">
                        </div>
                </div>
        </fieldset>
    <div class="submit-row">
    <input type="submit" value="Save">
    </div>
    </div>
    </form>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/add_exame.html
<h1>Cadastre Exame</h1>
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'save_exame'%}" method="post">
    {% csrf_token %}
        <div>
          <fieldset class="module aligned ">
                <div class="form-row field-id_exame">
                        <div>
                                <label class="required" for="id_id_exame">Id exame:</label>
                                    <input type="number" name="id_exame" class="vIntegerField" required="" id="id_id_exame">
                        </div>
                </div>
                <div class="form-row field-tipo">
                        <div>
                                <label class="required" for="id_tipo">Tipo:</label>
                                    <input type="text" name="tipo" class="vTextField" maxlength="255" required="" id="id_tipo">  
                        </div>
                </div>
                <div class="form-row field-virus">
                        <div>
                                <label class="required" for="id_virus">Virus:</label>
                                    <input type="text" name="virus" class="vTextField" maxlength="255" required="" id="id_virus">
                        </div>
                </div>
                <div class="form-row field-id_paciente">
                        <div>
                                <label class="required" for="id_id_paciente">Id paciente:</label>
                                    <div class="related-widget-wrapper">
            <select name="id_paciente" required="" id="id_id_paciente">
          <option value="" selected="">---------</option>
          {% for paciente in paciente_list %}
          <option value="{{paciente.id_paciente}}">{{paciente.cpf}}</option>
          {% endfor %}
<!--           
          
        
          <option value="2">Paciente object (2)</option>
        
          <option value="3">Paciente object (3)</option>
         -->
        </select>
        </div>       
                        </div>
                </div>
        </fieldset>
        <div class="submit-row">
                <input type="submit" value="Save">
        </div>
        </div>
    </form>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/add_paciente.html
<h1>Cadastre Paciente</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'save_paciente'%}" method="post">
    {% csrf_token %}
    <div>
      <fieldset class="module aligned ">
            <div class="form-row field-id_paciente">
                    <div>
                            <label class="required" for="id_id_paciente">Id paciente:</label>
                            
                                <input type="number" name="id_paciente" class="vIntegerField" required="" id="id_id_paciente">
                    </div>
            </div>
            <div class="form-row field-cpf">
                    <div>
                            <label class="required" for="id_cpf">Cpf:</label>
                                <input type="text" name="cpf" class="vTextField" maxlength="11" required="" id="id_cpf">
                    </div>
            </div>
            <div class="form-row field-nome">
                    <div>
                            <label class="required" for="id_nome">Nome:</label>
                                <input type="text" name="nome" class="vTextField" maxlength="255" required="" id="id_nome">
                    </div>
            </div>
            <div class="form-row field-endereco">
                    <div>
                            <label class="required" for="id_endereco">Endereco:</label>
                                <input type="text" name="endereco" class="vTextField" maxlength="255" required="" id="id_endereco">   
                    </div>
            </div>
            <div class="form-row field-nascimento">
                    <div>
                            <label class="required" for="id_nascimento">Nascimento(aaaa-mm-dd):</label>
                                <input type="text" name="nascimento" class="vDateField" size="10" required="" id="id_nascimento">
                    </div>
            </div>
    </fieldset>
    <div class="submit-row">
    <input type="submit" value="Save">
    </div>
    </div>
    </form>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/agregadoPEAs.html
{% if agregadoPEA_list %}
    <ul>
    {% for agregadoPEA in agregadoPEA_list %}
        <li><a href="{% url 'ag_detalhes' agregadoPEA.id %}">{{ agregadoPEA.id }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não tem agregadoPEAs.</p>
{%endif%}
<a href="{% url 'add_agregadoPEA'%}">Adicionar agregadoPEAs</a><br>
<a href="{% url 'index'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/amostra_detalhes.html
{{ amostra.codigo_amostra}}<br>
{{ amostra.metodo_de_coleta }}<br>
{{ amostra.material }}<br>
<li><a href="{% url 'change_amostra' amostra.id_amostra %}">Atualizar Amostra</a></li>
<li><a href="{% url 'delete_amostra' amostra.id_amostra %}" onclick="return confirm('Tem certeza que deseja deletar a amostra?')">Deletar Amostra</a></li>
<li><a href="{% url 'amostras'%}">Return</a></li>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/delete_amostra.html
<h1>Amostra deletado com sucesso!</h1>
<a href="{% url 'amostras'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/delete_exame.html
<h1>Exame deletado com sucesso!</h1>
<a href="{% url 'exames'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/delete_paciente.html
<h1>Paciente deletado com sucesso!</h1>
<a href="{% url 'pacientes'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/exame_agregadoPEA.html
{{ exame.id_exame }}<br>
{{ exame.tipo }}<br>
{{ exame.virus }}<br>
<a href="{% url 'p_detalhes' exame.id_paciente.id_paciente %}">Paciente: {{ exame.id_paciente.cpf }}</a>
<li><a href="{% url 'change_exame' exame.id_exame %}">Atualizar Exame</a></li>
<li><a href="{% url 'delete_exame' exame.id_exame %}" onclick="return confirm('Tem certeza que deseja deletar o exame?')">Deletar Exame</a></li>
<li><a href="{% url 'exames'%}">Return</a></li>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/exames.html
{% if exame_list %}
    <ul>
    {% for exame in exame_list %}
        <li><a href="{% url 'e_detalhes' exame.id_exame %}">{{ exame.id_exame }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não tem exames.</p>
{%endif%}
<a href="{% url 'add_exame'%}">Adicionar exames</a><br>
<a href="{% url 'index'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/index.html
<p><a href="{% url 'pacientes'%}">Pacientes</a></p>
<p><a href="{% url 'exames'%}">Exames</a></p>
<p><a href="{% url 'amostras'%}">Amostras</a></p>
<p><a href="{% url 'agregadoPEAs'%}">Paciente_amostra_exame</a></p>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/pacientes.html
{% if paciente_list %}
    <ul>
    {% for paciente in paciente_list %}
        <li><a href="{% url 'p_detalhes' paciente.id_paciente %}">{{ paciente.cpf }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>Não tem pacientes.</p>
{%endif%}
<a href="{% url 'add_paciente'%}">Adicionar pacientes</a><br>
<a href="{% url 'index'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/save_agregadoPEA.html
<h1>Cadastro de Agregado Paciente_amostra_exame bem sucedido!</h1>
<a href="{% url 'index'%}">Return</a>

ep3/gerenciamentoPEA/templates/gerenciamentoPEA/save_paciente.html
<h1>Cadastro bem sucedido!</h1>
{{ paciente.nome }}
{{ paciente.cpf }}
{{ paciente.endereco }}
{{ paciente.nascimento }}
<a href="{% url 'index'%}">Return</a>